stages:
  - lint
  - test

lint:
  stage: lint
  image:
    name: quay.io/redhat-aqe/angular:latest
  tags:
    - upshift
  script: 
    - npm install
    - npm run lint

test:
  stage: test
  image:
    name: quay.io/redhat-aqe/angular:latest
  tags:
    - upshift
  script: 
    - npm install
    - npm run test
