language: node_js
node_js:
  - 10
before_install:
  # Remove Red Hat npm registry definition
  - rm .npmrc
install:
  - npm install
script:
  - npm run lint
  - npm test

deploy:
  on:
    tags: true
  provider: npm
  edge: true
  cleanup: false
  api_key:
    secure: mBjIl6K+VtkTk92DoWjSAjedBTXYwBo8qkxAOeuY2kHyai8XRsEkBpF+YpCxuf7XQaRllpJoSA+2I73VjZklKAOgdEou2+rqu08Lkluzy8WaihYyMBcXUmpe72dD/Iiz4W7+v1GCa+mnNTesYTH1+1g3Vn2KXfDb4E/rrZjjWwpnbPxUvr3jXobJjfsFIymQTMG0GVlZrPtcUi9f+rmTMnHfYs7sGldz+wEWtFGBre/IciQPdc76xOi0JgzPttr/u9JzRcPhA551GsvOmsFmjDT2jMKLoYFbNoIKx8Nn+F1vQydY3ISbsArRCP8maXsG4ypR++jLkz6esEGPTPN0CnGuD977y/Mbe6YE5IMprChP+fc1rM7eNWsqQ3xD4uRExSstbFf6DoXxHUeQq+QVkb1zB/D0umIZIz5HPUVrVNYAndb87OSdBHfAjAY8fDReZogDrAxKW6Bnb25o6wVjqyPqK867B/3tDSRZ02N3/20s1AwlQzJO0xUVk2iPw2Qms4acGwiJKXGhbZkgEuH3kvRgz1bdf4FvjoWl8hG+EJzsoUseTkBjJNxEPgWXk67EyElqKP+gcOKeKhrmIEHgIN58wAJgKYy9HemoZEPUwJfaLdrxuC1kwM8Jm/j3IPn3GSTPvKgfupnevqaitZD7kKAo4iO4n/nJDV7J9Yk+CJo=
  email:
    secure: VjJcvvPKipH+wjSUHJUzFN84FrjhtM1tVk0fuagOfsx97Q0YG7o0mr7fVv12/67TgvD2j/uDtTEkEUB3pkdBqSCLnmuBShV4Ma0fkUfpCdj/RyRREzvIburBX0m4SBgSEu42WdOz2lqa6D93IkAbB6/w5bfa8Tn/DT6b498CikL2fmO7TFcnzz05hEOgJJX2WW6ZNhGDeLBV8eArEln48rdbq9Bb1DK96rg2kN7kVywHSBPfeEQxW6ZTN20BYSm1+MBlrLg90MHzthxEqKxNSx4wN67ITv32RcBkwqzQNvk2bfvkIqAu4U4/KzNmNtU5bvilTQC7nQr27A+11jdds9SxypRq1Y0tBtc2DQ53hRO1myyE91XoFDZsmY/J3uy2AhLU+bjSWuDABhzEw0U/xozrITlsLMJAWSSIgAswtxTPWtmriZjQDhyF+3QEX8OIPM/DTqRN4a54XwF3IPW1PyHUnIUqOV82wQg4VounNq93EDaDvcosA9xlWXFIvs9sY24xOuAxOZy21NkIw9FEmCX/h1k5AC2372h783U/DSGzJ0cJ1QPe+q37TT2J2Wf7swAK9yPRYyf2FAViflfEVFu9VMl1xuLgRP2o4R88+2v3m1GU6g8UvsJ4z8Y9xy3qL/zBewoQQfgIggjYP+zl0GtVTroxmzcIp26K7Tx5KgY=